/*
  Warnings:

  - The values [ARRAY,STRING,HASH_TABLE,MATH,SORTING,GREEDY,DEPTH_FIRST_SEARCH,BINARY_SEARCH,DATABASE,BREADTH_FIRST_SEARCH,TREE,BINARY_TREE,MATRIX,TWO_POINTERS,STACK,HEAP_PRIORITY_QUEUE,GRAPH,PREFIX_SUM,SIMULATION,DESIGN,COUNTING,BACKTRACKING,SLIDING_WINDOW,UNION_FIND,LINKED_LIST,ORDERED_SET,MONOTONIC_STACK,ENUMERATION,RECURSION,TRIE,DIVIDE_AND_CONQUER,BINARY_SEARCH_TREE,QUEUE,MEMOIZATION,GEOMETRY,SEGMENT_TREE,GAME_THEORY,HASH_FUNCTION,ROLLING_HASH,SHORTEST_PATH,COMBINATORICS,INTERACTIVE,CONCURRENCY,NUMBER_THEORY,MERGE_SORT,PROBABILITY_AND_STATISTICS,BRAINTEASER,MONOTONIC_QUEUE,RANDOMIZED,DATA_STREAM,BINARY_INDEXED_TREE,STRING_MATCHING] on the enum `ProblemCategory` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "ProblemCategory_new" AS ENUM ('ARRAYS_AND_STRINGS', 'LINKED_LISTS', 'TREES_AND_GRAPHS', 'DYNAMIC_PROGRAMMING', 'SORTING_AND_SEARCHING', 'STACK_AND_QUEUE', 'HASH_TABLES', 'RECURSION_AND_BACKTRACKING', 'BIT_MANIPULATION', 'MATH_AND_LOGIC');
ALTER TABLE "user_problems" ALTER COLUMN "categories" TYPE "ProblemCategory_new"[] USING ("categories"::text::"ProblemCategory_new"[]);
ALTER TYPE "ProblemCategory" RENAME TO "ProblemCategory_old";
ALTER TYPE "ProblemCategory_new" RENAME TO "ProblemCategory";
DROP TYPE "ProblemCategory_old";
COMMIT;
